Spline follow character movement
TheEmidee/UESplineFollow pull request #24
Opened 2024-08-12 14:54 UTC by VectorGamez

2024-08-14 07:10 UTC, Fr0oZzFred approved these changes

2024-08-22 08:26 UTC, TheEmidee requested changes

2024-08-22 08:26 UTC, TheEmidee commented on Source/SplineFollow/Private/Components/SFSplineFollowingComponent.cpp
> +    GetOwner()->SetActorLocation( new_location );
There's a SetActorLocationAndRotation

2024-08-22 08:27 UTC, VectorGamez commented on Source/SplineFollow/Private/Components/SFSplineFollowingComponent.cpp
> +    GetOwner()->SetActorLocation( new_location );
Done.

2024-08-22 08:28 UTC, merged