Wait spline follower reaches position - with interface
TheEmidee/UESplineFollow pull request #44
Opened 2024-12-19 01:43 UTC by FXIce18

Updated WaitSplineFollowerReachesPosition GA Task so it can work with a generic SplineFollowingInterface instead of SplineFollowingMovementComponent only.

Moved FPositionObservert structure to SplineFollowingInterface.

Implemented ProcessPositionObservers in SplineFollowingComponent.

2025-01-10 10:02 UTC, Fr0oZzFred approved these changes

2025-01-10 10:02 UTC, Fr0oZzFred commented on Source/SplineFollow/Private/Components/SFSplineFollowingComponent.cpp
>  }
empty line added in
https://github.com/TheEmidee/UESplineFollow/pull/45

2025-01-10 13:22 UTC, Frickerson requested changes

2025-01-10 13:22 UTC, Frickerson commented on Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h
> +    virtual void RegisterPositionObserver( const FSWOnSplineFollowingReachedPositionDelegate & delegate, float normalized_position, bool trigger_once = true ) override;
no virtual for overridden functions

2025-01-16 12:45 UTC, FXIce18 commented on Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h
> +    virtual void RegisterPositionObserver( const FSWOnSplineFollowingReachedPositionDelegate & delegate, float normalized_position, bool trigger_once = true ) override;
Done !

2025-01-16 13:13 UTC, Frickerson approved these changes

2025-01-17 09:01 UTC, merged